const {chromium, browserOptions}=require('./tools/browser.cjs');
const path=require('path'),fs=require('fs'),{pathToFileURL}=require('url');
let browser;
(async()=>{
 browser=await chromium.launch(browserOptions());
 const page=await browser.newPage({viewport:{width:1040,height:940}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 await page.goto(pathToFileURL(path.join(__dirname,'PRIMAL_RUN_Demo_v2/demo.html')).href);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Static poses'));
 const check=(value,message)=>{if(!value)throw Error(message);};
 const start=await page.evaluate(()=>primalDemo.getState().player.x);
 await page.keyboard.down('KeyD');await page.waitForTimeout(500);await page.keyboard.up('KeyD');
 const end=await page.evaluate(()=>primalDemo.getState().player.x);check(end>start+40,'Keyboard movement failed');
 await page.evaluate(()=>{const s=primalDemo.getState();s.enemies=[{x:s.player.x+30,y:s.player.y,touch:0}];s.cooldown=0;});
 await page.keyboard.press('Space');await page.waitForTimeout(50);
 check(await page.evaluate(()=>primalDemo.getState().hunts===1&&primalDemo.getState().enemies.length===0),'Bite failed to remove nearby enemy');
 await page.evaluate(()=>{const s=primalDemo.getState();s.health=30;s.food=[{x:s.player.x,y:s.player.y}];primalDemo.step(0);});
 check(await page.evaluate(()=>primalDemo.getState().health===44),'Food health restoration failed');
 await page.evaluate(()=>{primalDemo.getState().health=0;primalDemo.step(0);});
 check(await page.evaluate(()=>primalDemo.getState().ended),'Death failed');
 await page.keyboard.press('KeyR');await page.waitForTimeout(30);
 check(await page.evaluate(()=>primalDemo.getState().health===100&&!primalDemo.getState().ended),'Restart failed');
 await page.evaluate(()=>{const s=primalDemo.getState();s.player={x:195,y:198};s.enemies=[];});
 await page.keyboard.down('KeyD');await page.waitForTimeout(600);await page.keyboard.up('KeyD');
 check(await page.evaluate(()=>{const p=primalDemo.getState().player;return Math.hypot(p.x-236,p.y-198)>=31.9;}),'Rock collision failed');
 await page.keyboard.press('KeyR');await page.waitForTimeout(80);
 await page.screenshot({path:path.join(__dirname,'PRIMAL_RUN_Demo_v2/demo_screenshot.png')});
 check(!errors.length,'Runtime errors: '+errors.join('; '));
 const report={result:'PASS',engine:'headless Chromium browser demo, not GDevelop',checks:['six sprites loaded','keyboard movement','bite removes nearby enemy','food heals','death','restart','rock collision','no page errors']};
 fs.writeFileSync(path.join(__dirname,'PRIMAL_RUN_Demo_v2/browser_test_report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
