'use strict';const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {chromium,browserOptions,localURL}=require('../tools/browser.cjs');
(async()=>{const b=await chromium.launch(browserOptions());const errors=[];try{const p=await b.newPage({viewport:{width:1280,height:900}});p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.env.PRIMAL_GAME_URL||await localURL(path.resolve(__dirname,'../PRIMAL_RUN_Game/index.html')));await p.locator('[data-first-language="da"]').click({timeout:2000}).catch(()=>{});await p.waitForFunction(()=>primalRun&&document.querySelector('[data-action=start]:not(:disabled)'));
 await p.locator('[data-action=settings]').click();assert.equal(await p.evaluate(()=>primalRun.audio.context.state),'running');assert.equal(await p.evaluate(()=>primalRun.audio.trackId),'menu');await p.locator('[data-action=back]').click();await p.locator('[data-action=start]').click();await p.locator('[data-action=begin]').click();await p.waitForFunction(()=>primalRun.audio.trackId==='forest');
 // Capture actual oscillator creation, not just the selected theme name.
 await p.evaluate(()=>{const a=primalRun.audio,old=a.tone.bind(a);window.musicCalls=[];a.tone=(...args)=>{musicCalls.push({frequency:args[0],time:args[1],wave:args[4],track:a.trackId,band:a.healthBand});return old(...args)};});
 const themes=[];for(let stage=0;stage<4;stage++)for(const boss of [false,true]){
  await p.evaluate(({stage,boss})=>{const g=primalRun.game,r=g.run;g.phase='playing';r.stage=stage;r.bossSpawned=boss;r.bossDefeated=false;r.enemies=[];r.spawnTimer=999;r.meat=0;r.invulnerable=999;r.health=r.maxHealth;primalRun.update(performance.now());},{stage,boss});
  const track=boss?'boss'+stage:['forest','river','rocks','volcano'][stage];await p.waitForFunction(track=>primalRun.audio.trackId===track,track);await p.waitForFunction(track=>musicCalls.some(c=>c.track===track),track);themes.push(track);
 }
 for(const [fraction,band]of [[.49,1],[.24,2],[.09,3]]){await p.evaluate(f=>{const r=primalRun.game.run;r.health=r.maxHealth*f;primalRun.update(performance.now());},fraction);assert.equal(await p.evaluate(()=>primalRun.audio.healthBand),band);assert.equal(await p.evaluate(()=>primalRun.audio.trackId),'boss3');}
 await p.evaluate(()=>{primalRun.game.pause();primalRun.update(performance.now())});assert.equal(await p.evaluate(()=>primalRun.audio.ducked),true);assert.equal(await p.evaluate(()=>primalRun.audio.trackId),'boss3');
 // Key was already down when combat opened the choice screen. Keyup must not click it.
 await p.evaluate(()=>{const g=primalRun.game;g.phase='playing';g.run.stage=0;g.run.bossSpawned=false;g.run.health=g.run.maxHealth;});await p.keyboard.down('Space');await p.evaluate(()=>{primalRun.game.addXP(primalRun.game.run.nextXP);primalRun.update(performance.now())});await p.waitForSelector('[data-mutation]');await p.keyboard.up('Space');for(let i=0;i<5;i++)await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>primalRun.game.phase),'mutation');assert.equal(await p.evaluate(()=>Object.values(primalRun.game.run.mutations).reduce((a,b)=>a+b,0)),0);
 await p.keyboard.press('Digit2');await p.waitForFunction(()=>primalRun.game.phase==='playing');assert.equal(await p.evaluate(()=>Object.values(primalRun.game.run.mutations).reduce((a,b)=>a+b,0)),1);
 await p.keyboard.down('Space');await p.evaluate(()=>{const g=primalRun.game,r=g.run;r.bossDefeated=true;g.phase='cleared';primalRun.update(performance.now());});await p.waitForSelector('[data-action=next]');await p.keyboard.up('Space');for(let i=0;i<5;i++)await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>primalRun.game.phase),'cleared');assert.equal(await p.evaluate(()=>primalRun.game.run.stage),0);await p.keyboard.press('Enter');await p.waitForFunction(()=>primalRun.game.run.levelIndex===1&&primalRun.game.phase==='playing');
 const openings=[];for(let i=0;i<3;i++){await p.evaluate(()=>{const g=primalRun.game;g.start();g.run.enemies=[];g.run.spawnTimer=999;g.pause();primalRun.update(performance.now());});openings.push(await p.evaluate(()=>JSON.stringify({seed:primalRun.game.run.seed,rocks:primalRun.game.run.map.rocks.slice(0,8),groves:primalRun.game.run.map.groves})));}assert.equal(new Set(openings).size,3);
 const rendered=await p.evaluate(async()=>{
  const result=[];
  for(const id of ['menu','forest','river','rocks','volcano','boss0','boss1','boss2','boss3','boss3:1','boss3:2','boss3:3']){
   const offline=new OfflineAudioContext(1,22050*2,22050),a=new PrimalAudio(x=>x,{master:1,music:1,sfx:1});a.trackId=id.split(':')[0];a.healthBand=Number(id.split(':')[1]||0);a.bus=offline.createGain();a.bus.connect(offline.destination);a.context={state:'running',currentTime:0,createOscillator:()=>offline.createOscillator(),createGain:()=>offline.createGain()};
   for(let i=0;i<18;i++){a.context.currentTime=i*.1;a.schedule();}const data=(await offline.startRendering()).getChannelData(0);let sum=0,peak=0;for(const v of data){sum+=v*v;peak=Math.max(peak,Math.abs(v));}const digest=await crypto.subtle.digest('SHA-256',data.buffer);result.push({id,rms:Math.sqrt(sum/data.length),peak,hash:[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('')});
  }return result;
 });assert.equal(new Set(rendered.map(r=>r.hash)).size,12,'nine themes plus three distinct health-layer waveforms');assert.ok(rendered.every(r=>r.rms>.001&&r.peak<1),'audible music without sample clipping');
 assert.ok(await p.evaluate(()=>musicCalls.length>10));assert.equal(await p.evaluate(()=>primalRun.audio.error),null);if(process.env.PRIMAL_EXPECT_GDEVELOP)assert.equal(await p.evaluate(()=>typeof gdjs.RuntimeGame),'function');assert.deepEqual(errors,[]);
 const report={status:'PASS',runtime:process.env.PRIMAL_EXPECT_GDEVELOP?'official GDevelop GDJS 5.6.283':'standalone Chromium',themes,rendered,checks:['actual WebAudio tones for all biome/boss themes','health50/25/10 layers coexist with boss','paused score duck','held Space released on mutation and cleared screens cannot click','repeated Space cannot select/skip','Digit2 chooses; Enter deliberately advances','three successive starts have different layouts','no page/audio errors']};if(process.env.PRIMAL_ADAPTIVE_REPORT)fs.writeFileSync(process.env.PRIMAL_ADAPTIVE_REPORT,JSON.stringify(report,null,2)+'\n');console.log('PASS: adaptive music, health layers, Space selection guard and fresh-run layouts');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
