'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(species='compy'){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);g.start({seed:24});g.run.enemies=[];g.run.spawnTimer=999;g.run.map.rocks=[];g.run.map.events=[];return g;}
test('food spoils in portions and disappears with corpse, while pause freezes decay',()=>{const g=setup(),r=g.run,e=g.spawn('tyrannosaurus',{x:1000,y:900});g.kill(e);r.enemies=[];const food=r.pickups.find(p=>p.corpseId===e.id),original=food.value;g.decayCorpses(7);assert.equal(food.value,original);g.decayCorpses(2.5);assert.equal(food.value,original-1);g.pause();const before=JSON.stringify(r);g.step(.05);assert.equal(JSON.stringify(r),before);g.resume();g.decayCorpses(9);assert.ok(!r.pickups.includes(food));g.decayCorpses(60);assert.equal(r.corpses.length,0);assert.ok(!r.pickups.includes(food));});
test('escape regeneration needs distance, ten seconds, no combat and no bleed; bosses never regen',()=>{const g=setup(),r=g.run,e=g.spawn('parasaurolophus',{x:1100,y:900});e.hp=e.maxHP/2;e.alert=false;e.lastAttackedAt=0;r.seconds=9;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP/2);r.seconds=11;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP*.525);e.alert=true;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP*.525);e.alert=false;e.bleed=1;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP*.525);e.bleed=0;e.boss=true;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP*.525);e.boss=false;e.x=r.player.x;e.y=r.player.y;g.regenerateEnemy(e,1);assert.equal(e.hp,e.maxHP*.525);});
test('predators prefer food clusters, walk gradually and consume without player rewards',()=>{const g=setup(),r=g.run;for(const x of [1300,1320,1500]){const prey=g.spawn('parasaurolophus',{x,y:900});g.kill(prey);}r.enemies=[];const predator=g.spawn('carnotaurus',{x:1250,y:900});predator.alert=false;assert.ok(g.carrionTarget(predator).x<1400);const start=predator.x;g.scavenge(predator,.1);assert.ok(predator.x>start&&predator.x<start+10);predator.x=1300;const meat=r.pickups.filter(p=>p.corpseId!==undefined).reduce((n,p)=>n+p.value,0);g.scavenge(predator,2);assert.equal(r.pickups.filter(p=>p.corpseId!==undefined).reduce((n,p)=>n+p.value,0),meat-1);assert.equal(r.totalMeat,0);assert.equal(r.xp,0);const herb=g.spawn('triceratops',{x:1300,y:900});assert.equal(g.carrionTarget(herb),null);predator.boss=true;assert.equal(g.carrionTarget(predator),null);});
test('T rex unlock persists and slow attack locks heading before heavy contact',()=>{const g=setup('tyrannosaurus'),r=g.run;r.player.facing='E';const e=g.spawn('tyrannosaurus',{x:540,y:340}),hp=e.hp;g.attack();assert.equal(r.attackCooldown,1.6);g.advanceAttack(.5);assert.equal(e.hp,hp);r.player.facing='W';g.advanceAttack(.06);assert.ok(e.hp<hp-30);const hit=e.hp;g.advanceAttack(.5);assert.equal(e.hp,hit);assert.equal(C.sanitizeSave(g.save).selectedSpecies,'tyrannosaurus');for(const d of ['N','E','S','W'])assert.ok(C.playerFrame('tyrannosaurus','walk',d,0).includes('enemy_full/tyrannosaurus'));});
test('stationary T rex roar spends stamina, scares normals and leaves boss unchanged',()=>{const g=setup('tyrannosaurus'),r=g.run,e=g.spawn('compy',{x:620,y:340}),boss=g.spawn('carnotaurus',{x:630,y:340},true);r.mutations.rexVoice=2;g.step(.01,{pounce:true});assert.equal(r.stamina,50);assert.ok(e.scaredUntil>=3);assert.equal(boss.scaredUntil,undefined);const x=e.x;g.enemyStep(e,.05);assert.ok(e.x>x);});
test('digestion DNA upgrade migrates safely, costs DNA and improves feeding',()=>{const legacy=C.sanitizeSave({upgrades:{health:2},dna:100});assert.equal(legacy.upgrades.health,2);assert.equal(legacy.upgrades.digestion,0);const g=setup();g.phase='shop';g.save.dna=100;assert.ok(g.purchase('digestion'));assert.equal(g.save.dna,100-C.upgradeCost(0));g.start({seed:24});g.run.enemies=[];g.run.map.rocks=[];const e=g.spawn('carnotaurus',{...g.run.player});g.kill(e);g.run.enemies=[];g.eat(.3,{eat:true});assert.ok(g.run.eating.progress>.5);});
