'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(species='compy'){const g=new C.Game({random:()=>.9});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);g.start({seed:33});Object.assign(g.run,{enemies:[],spawnTimer:999});Object.assign(g.run.map,{rocks:[],cover:[],mud:[],events:[],sites:[]});return g;}
test('abilities consume their full stamina cost and recovery pauses after casting',()=>{for(const species of Object.keys(C.PLAYER_SPECIES)){const g=setup(species),r=g.run;g.step(.02,{x:1,pounce:true});assert.equal(r.stamina,100-C.PLAYER_SPECIES[species].abilityCost);const after=r.stamina;for(let i=0;i<20;i++)g.step(.05);assert.equal(r.stamina,after);g.phase='mutation';const frozen=JSON.stringify(r);g.step(.05);assert.equal(JSON.stringify(r),frozen);}});
test('herbivores eat plants and ignore corpse meat, including exploration rewards',()=>{const g=setup('ankylosaurus'),r=g.run;r.map.forage=[{id:'plant:test',kind:'plant',x:480,y:340,rarity:1,value:2,depleted:false}];r.pickups=[{id:1,kind:'meat',value:9,x:480,y:340}];for(let i=0;i<13;i++)g.step(.05,{eat:true});assert.equal(r.totalMeat,1);assert.equal(r.pickups[0].value,9);r.map.sites=[{id:7,x:480,y:340,claimed:false}];r.activeSite=7;g.phase='exploration';g.explore(true);assert.ok(r.map.forage.some(p=>p.id==='plant:site:7'&&p.value===8));});
test('ordinary large predators telegraph before contact damage',()=>{for(const kind of ['triceratops','tyrannosaurus','deinosuchus']){const g=setup(),r=g.run,e=g.spawn(kind,{x:500,y:340});g.provoke(e);e.cooldown=0;const hp=r.health;g.enemyStep(e,.02);assert.equal(e.mode,'windup',kind);assert.ok(e.timer>=.8);assert.equal(r.health,hp);g.enemyStep(e,.3);assert.equal(r.health,hp);}});
test('all herbivorous NPCs graze when unprovoked',()=>{for(const kind of ['parasaurolophus','ankylosaurus','triceratops']){const g=setup(),e=g.spawn(kind,{x:1000,y:700});e.naturalTime=0;g.naturalBehavior(e,.02);assert.equal(e.mode,'graze');}});
test('legendary shield absorbs final damage after armour and stance',()=>{const g=setup('ankylosaurus'),r=g.run;r.mutations.armor=3;r.pounce=1;r.shield=20;r.shieldTime=4;const hp=r.health;g.damage(100);assert.equal(r.health,hp);assert.equal(r.shield,1);});
test('legendary mutation pool contains one shared and one per playable species',()=>{const legendary=C.MUTATIONS.filter(m=>m.rarity==='legendary');assert.equal(legendary.length,Object.keys(C.PLAYER_SPECIES).length+1);assert.equal(legendary.filter(m=>!m.species).length,1);for(const species of Object.keys(C.PLAYER_SPECIES))assert.equal(legendary.filter(m=>m.species===species).length,1);});
