'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies('deinosuchus');g.start({seed:123});g.run.enemies=[];g.run.spawnTimer=999;g.run.map.rocks=[];return g;}
test('Deinosuchus unlocks from Doris and preserves existing selected species',()=>{const g=new C.Game();g.start({seed:123});assert.ok(!g.save.unlockedSpecies.includes('deinosuchus'));g.checkAchievements({bossKind:'deinosuchus'});assert.ok(!g.save.unlockedSpecies.includes('deinosuchus'));g.run.levelIndex=3;g.checkAchievements({bossKind:'deinosuchus'});assert.ok(g.save.unlockedSpecies.includes('deinosuchus'));g.phase='menu';assert.ok(g.selectSpecies('deinosuchus'));const raw=JSON.stringify(g.save);const h=new C.Game({storage:{getItem:()=>raw,setItem(){}}});assert.equal(h.save.selectedSpecies,'deinosuchus');assert.ok(h.save.unlockedSpecies.includes('deinosuchus'));});
test('Deinosuchus shares 120 existing native frames and has all five personal rarities',()=>{for(const dir of ['S','N','E','W'])for(const state of ['idle','walk','run','attack','hurt','death'])assert.ok(C.playerFrame('deinosuchus',state,dir,0).startsWith('assets/enemy_full/deinosuchus_'));assert.deepEqual(new Set(C.MUTATIONS.filter(m=>m.species==='deinosuchus').map(m=>m.rarity)),new Set(['common','uncommon','rare','epic','legendary']));});
test('maw rush spends stamina once, hits each enemy once and does not grant invulnerability',()=>{const g=setup(),r=g.run,e=g.spawn('carnotaurus',{x:r.player.x+40,y:r.player.y});e.hp=e.maxHP=500;g.step(.01,{x:1,pounce:true});assert.equal(r.stamina,52);assert.equal(r.stats.abilities,1);assert.equal(e.hp,475);g.step(.01,{x:1,pounce:true});assert.equal(e.hp,475);assert.equal(r.stats.abilities,1);g.damage(10,e);assert.equal(r.health,170);g.pause();const frozen=JSON.stringify(r);g.step(.05,{x:1,pounce:true});assert.equal(JSON.stringify(r),frozen);});
test('water mobility and jaw/rush mutations implement real tradeoffs',()=>{const g=setup(),r=g.run;r.stage=1;r.map.riverCurve=r.map.river=[{x:0,y:340},{x:4000,y:340}];r.map.ponds=[];r.map.fords=[];assert.equal(g.terrainAt(r.player).speed,1.35);r.mutations.crocCurrent=2;assert.equal(g.terrainAt(r.player).speed,1.35*1.16);r.mutations.crocJaw=2;g.attack();assert.equal(r.attackDuration,1.15*1.16);r.attack=null;r.attackCooldown=0;const e=g.spawn('carnotaurus',{x:r.player.x+40,y:r.player.y});e.hp=e.maxHP=500;g.resolveBite('E');assert.equal(e.hp,500-25*1.3);r.mutations.crocEconomy=3;assert.equal(C.abilityCost(r),39);r.mutations.crocAncient=1;r.hitStop=0;g.step(.01,{x:1,pounce:true});assert.equal(r.shield,20);assert.equal(r.shieldTime,4);});
test('Deinosuchus remains a carnivore and cannot catch fish',()=>{const g=setup(),r=g.run;assert.equal(C.PLAYER_SPECIES.deinosuchus.diet,'carnivore');const school={x:r.player.x,y:r.player.y,stock:5};r.map.fishSchools=[school];assert.equal(g.catchFish(school),0);assert.equal(school.stock,5);});
test('epic maw-rush mutation increases contact damage and slows only land travel',()=>{const baseline=setup(),mutated=setup();for(const g of [baseline,mutated]){g.run.map.ponds=[];g.run.map.mud=[];}mutated.run.mutations.crocRush=2;const x=baseline.run.player.x,y=mutated.run.player.x;baseline.step(.02,{x:1});mutated.step(.02,{x:1});assert.ok(Math.abs((mutated.run.player.x-y)/(baseline.run.player.x-x)-.9)<1e-8);const r=mutated.run,e=mutated.spawn('carnotaurus',{x:r.player.x+40,y:r.player.y});e.hp=e.maxHP=500;mutated.step(.01,{x:1,pounce:true});assert.equal(e.hp,459);assert.equal(r.invulnerable,0);});
