'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(){const g=new C.Game({random:()=>.1});g.start({seed:42});g.run.enemies=[];g.run.spawnTimer=999;g.run.map.events=[];g.run.map.rocks=[];return g;}
function food(g,kind='carnotaurus'){const e=g.spawn(kind,{...g.run.player});g.kill(e);g.run.enemies=[];return g.run.pickups.find(p=>p.kind==='meat');}
function advance(g,n,input){for(let i=0;i<n;i++)g.step(.05,input);}
test('corpse meat requires stationary held eating, awards portions and preserves leftovers',()=>{const g=setup(),r=g.run,p=food(g);advance(g,14,{});assert.equal(r.meat,0);advance(g,8,{eat:true});assert.equal(r.meat,0);g.step(.05,{eat:true,x:1});assert.equal(r.eating,null);advance(g,13,{eat:true});assert.equal(r.meat,1);assert.equal(p.value,4);const stamina=r.stamina;advance(g,3,{eat:true});g.damage(5);assert.equal(r.eating,null);assert.equal(r.stamina,stamina);advance(g,5,{eat:true});assert.equal(r.meat,1);advance(g,20,{eat:true});assert.ok(r.meat>1);});
test('attacks cancel eating, choices freeze its clock, corpse expiry removes linked leftovers',()=>{const g=setup(),r=g.run,p=food(g);advance(g,4,{eat:true});g.step(.05,{eat:true,attack:true});assert.equal(r.eating,null);r.attack=null;r.attackCooldown=0;advance(g,4,{eat:true});g.pause();const before=JSON.stringify(r);advance(g,20,{eat:true});assert.equal(JSON.stringify(r),before);g.resume();r.corpses[0].age=r.corpses[0].lifetime-.01;g.step(.05,{eat:true});assert.equal(r.corpses.length,0);assert.ok(!r.pickups.includes(p));assert.equal(r.eating,null);});
test('exploration reveals bounded cells and rare discoveries award once; stage clears fog',()=>{const g=setup(),r=g.run;g.step(.05);assert.ok(Object.keys(r.explored).length>0);r.map.events=[{...r.player,type:'fossil',claimed:false}];g.step(.05);assert.equal(r.dna,2);g.step(.05);assert.equal(r.dna,2);g.phase='cleared';g.nextStage();assert.deepEqual(r.explored,{});});
test('seed reproduces events and alternative arenas; settings and duplicate bindings stay safe',()=>{assert.deepEqual(C.createMap(1,22).events,C.createMap(1,22).events);assert.notDeepEqual(C.createMap(1,22).arenas,C.createMap(1,23).arenas);const g=setup();assert.equal(g.setBinding('eat','KeyQ'),true);assert.equal(g.setBinding('attack','KeyQ'),false);g.setSetting('hudScale',20);assert.equal(g.save.settings.hudScale,1.4);g.setSetting('ambient',-1);assert.equal(g.save.settings.ambient,0);g.setSetting('autoAttack',true);assert.equal(g.save.settings.autoAttack,true);});

test('boss arena clearing removes matching cover, while explicit spawns leave the world unchanged',()=>{const g=setup(),r=g.run;const before=r.map.cover.length;g.spawn('carnotaurus',{x:700,y:500},true);assert.equal(r.map.cover.length,before);r.enemies=[];r.map.rocks=[];const arena=r.map.arenas[0];assert.ok(arena);r.map.cover.push({x:arena.x,y:arena.y,radius:34});r.map.decorations.push({x:arena.x,y:arena.y,path:'assets/ecology/shrub.png'});const boss=g.spawn('carnotaurus',null,true);assert.ok(boss.arenaStyle);assert.ok(!r.map.cover.some(p=>p.x===boss.x&&p.y===boss.y));assert.ok(!r.map.decorations.some(p=>p.x===boss.x&&p.y===boss.y));});
