'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {chromium,browserOptions,localURL}=require('../tools/browser.cjs');
(async()=>{const browser=await chromium.launch(browserOptions());try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(await localURL(path.resolve(__dirname,'../PRIMAL_RUN_Game/index.html')));await page.waitForSelector('[data-action="start"]:not(:disabled)');await page.locator('[data-action="start"]').click();await page.locator('[data-action="begin"]').click();await page.waitForFunction(()=>primalRun.game.phase==='playing');
 const report=await page.evaluate(async()=>{const g=primalRun.game,r=g.run,canvas=document.querySelector('canvas[aria-label]'),ctx=canvas.getContext('2d'),old=ctx.drawImage,seen=new Set(),tiles=[];ctx.drawImage=function(im,...args){if(im.src?.includes('/ground/')){seen.add(im.src.split('/').pop());if(im.width===32&&args.length!==2)throw Error('Ground tile resized');}return old.call(this,im,...args);};try{g.pause();for(let stage=0;stage<4;stage++){await primalRun.preload({stage});r.stage=stage;r.map=PrimalCore.createMap(stage,7300);r.player.x=1700;r.player.y=1200;g.setView(canvas.width,canvas.height);primalRun.update(performance.now());tiles.push({stage,draws:[...seen].filter(f=>f.startsWith(['forest','river','rocks','volcano'][stage]))});}return{tiles,starter:r.species,smoothing:ctx.imageSmoothingEnabled};}finally{ctx.drawImage=old;}});assert.equal(report.starter,'deinonychus');assert.equal(report.smoothing,false);assert.ok(report.tiles.every(t=>t.draws.length>=2));
 const previews=path.resolve(__dirname,'../PRIMAL_RUN_Game/previews/evolution');fs.mkdirSync(previews,{recursive:true});for(let stage=0;stage<4;stage++){await page.evaluate(stage=>{const g=primalRun.game,r=g.run;r.stage=stage;r.map=PrimalCore.createMap(stage,7300);r.enemies=[];r.player.x=stage===3&&r.map.volcanoes.length?r.map.volcanoes[0].x:1700;r.player.y=stage===3&&r.map.volcanoes.length?r.map.volcanoes[0].y:1200;g.setView(document.querySelector('canvas[aria-label]').width,document.querySelector('canvas[aria-label]').height);primalRun.update(performance.now());},stage);await page.locator('.screen').evaluate(s=>s.style.visibility='hidden');await page.locator('canvas[aria-label]').screenshot({path:path.join(previews,'biome_'+stage+'.png')});await page.locator('.screen').evaluate(s=>s.style.visibility='');}
 await page.evaluate(()=>{const g=primalRun.game,r=g.run;r.stage=3;r.levelIndex=7;g.phase='cleared';primalRun.update(performance.now());});await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>primalRun.game.phase),'cleared');await page.locator('[data-action="next"]').click();await page.waitForSelector('.end-scene[data-scene="meteor"]').catch(async e=>{console.error({errors,state:await page.evaluate(()=>({phase:primalRun.game.phase,extinction:primalRun.game.run.extinction,scene:document.querySelector('.end-scene')?.outerHTML,body:document.querySelector('.screen')?.innerText.slice(0,300)}))});throw e;});assert.match(await page.locator('.panel').innerText(),/DNA og din score lever videre/);assert.equal(await page.evaluate(()=>primalRun.audio.trackId),'extinction');const snapshot=await page.evaluate(()=>JSON.stringify(primalRun.game.run.stats));await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>primalRun.game.phase),'result');await page.waitForTimeout(4700);assert.equal(await page.evaluate(()=>JSON.stringify(primalRun.game.run.stats)),snapshot);await page.locator('.end-scene').screenshot({path:path.join(previews,'meteor_impact.png')});await page.evaluate(()=>primalRun.game.setSetting('reducedMotion',true));await page.waitForTimeout(100);await page.locator('.end-scene').screenshot({path:path.join(previews,'meteor_reduced_motion.png')});assert.equal(await page.evaluate(()=>primalRun.game.run.result.victory),true);assert.deepEqual(errors,[]);
 const evidence={status:'PASS',runtime:'standalone Chromium',...report,checks:['Native biome tiles are actually drawn without resize/smoothing','Four actual biome screenshots','Space cannot advance final cleared/result screens','Earned victory keeps score/DNA and freezes simulation telemetry','Meteor scene and distinct extinction music','Reduced-motion static finale'],production_approved:false};fs.writeFileSync(path.resolve(__dirname,'../PRIMAL_RUN_Game/evolution_runtime_report.json'),JSON.stringify(evidence,null,2)+'\n');console.log('PASS: starter/native ground/final Space guard/meteor music/reduced motion');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
