'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core');
function make(id='deinonychus'){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(id);g.start({seed:42});g.run.enemies=[];g.run.map.rocks=[];g.run.spawnTimer=999;return g;}
test('new feathered starter preserves all legacy species, DNA, upgrades and chosen animal',()=>{for(const species of Object.keys(C.PLAYER_SPECIES)){const s=C.sanitizeSave({selectedSpecies:species,unlockedSpecies:[species],dna:321,upgrades:{health:3}});assert.equal(s.selectedSpecies,species);assert.equal(s.dna,321);assert.equal(s.upgrades.health,3);assert.ok(s.unlockedSpecies.includes('deinonychus'));}assert.equal(new C.Game().save.selectedSpecies,'deinonychus');});
test('all species have personal common/uncommon/rare/epic/legendary mutations and capped foreign choices remain excluded',()=>{assert.equal(new Set(C.MUTATIONS.map(m=>m.id)).size,C.MUTATIONS.length);for(const species of Object.keys(C.PLAYER_SPECIES)){for(const rarity of Object.keys(C.MUTATION_RARITIES))assert.ok(C.MUTATIONS.some(m=>m.species===species&&m.rarity===rarity),species+'/'+rarity);const g=make(species);for(const m of C.MUTATIONS)if(!m.species||m.species===species)g.run.mutations[m.id]=m.max;g.addXP(6);assert.equal(g.phase,'playing');assert.equal(g.run.choices.length,0);}});
test('Deinonychus feint costs stamina, deals no collision damage and empowers exactly one flank bite',()=>{const g=make(),r=g.run,e=g.spawn('tyrannosaurus',{x:535,y:340});e.speed=0;e.cooldown=999;e.mode="recover";e.timer=9;e.facingX=1;e.facingY=0;r.player.facing='E';const hp=e.hp;g.step(.01,{x:1,pounce:true});assert.equal(e.hp,hp);assert.equal(r.stamina,74);assert.ok(r.precisionTime>0);g.resolveBite('E');assert.equal(hp-e.hp,13.5);assert.equal(r.precisionTime,0);const before=e.hp;g.resolveBite('E');assert.equal(before-e.hp,9);});
test('feint flank bonus fails against the front and its clock freezes in mutation menus',()=>{const g=make(),r=g.run,e=g.spawn('tyrannosaurus',{x:530,y:340});e.facingX=-1;e.facingY=0;r.precisionTime=2;const hp=e.hp;g.phase='mutation';g.step(.05);assert.equal(r.precisionTime,2);g.phase='playing';g.resolveBite('E');assert.equal(hp-e.hp,9);});
test('added species traits change real cost, cooldown, feeding and flank damage while NPC baselines stay unchanged',()=>{const g=make('velociraptor'),r=g.run;r.mutations.velociraptor_common=3;assert.equal(C.abilityCost(r),26);assert.equal(C.traitBonus(r,'abilityCost'),-6);r.mutations.velociraptor_uncommon=2;assert.equal(C.traitBonus(r,'feeding'),.3);r.mutations.velociraptor_epic=2;const e=g.spawn('tyrannosaurus',{x:530,y:340});e.facingX=1;e.facingY=0;const hp=e.hp;g.resolveBite('E');assert.ok(Math.abs(hp-e.hp-8*1.3)<1e-8);});
test('lava gives a grace warning then hurts, pauses freeze heat; natural basalt crossings and all fish remain safe',()=>{const g=make(),r=g.run;r.stage=3;r.map=C.createMap(3,42);r.enemies=[];const p=r.map.riverCurve.find(p=>!r.map.lavaCrossings.some(c=>Math.hypot(c.x-p.x,c.y-p.y)<80));Object.assign(r.player,p);for(let i=0;i<18;i++)g.step(.05);assert.equal(r.health,100);assert.ok(r.heat>.8);g.phase='mutation';const heat=r.heat;g.step(.05);assert.equal(r.heat,heat);g.phase='playing';for(let i=0;i<8;i++)g.step(.05);assert.ok(r.health<100);for(const c of r.map.lavaCrossings)assert.equal(C.isLava(3,r.map,c),false);for(let seed=1;seed<=24;seed++){const m=C.createMap(3,seed);assert.equal(C.isLava(3,m,{x:480,y:340}),false);for(const f of m.fishSchools)assert.ok(C.isWater(3,m,f,14)&&!C.isLava(3,m,f));for(const v of m.volcanoes)assert.ok(Math.hypot(v.x-480,v.y-340)>1300);}});
test('only completed eight-level journeys receive extinction cinematic; victory/rewards are recorded exactly once',()=>{const g=make(),r=g.run;r.levelIndex=7;g.phase='cleared';g.nextStage();assert.equal(r.extinction,true);assert.equal(r.result.victory,true);const score=r.result.score;g.finish(true);assert.equal(g.save.scores.length,1);assert.equal(r.result.score,score);const secret=make();secret.start({seed:1993});secret.phase='cleared';secret.nextStage();assert.equal(secret.run.extinction,false);const classic=make();classic.start({campaign:'classic'});classic.run.levelIndex=3;classic.phase='cleared';classic.nextStage();assert.equal(classic.run.extinction,false);});
test('simulator records actual granted species/legendary mutations separately from earned mutations',()=>{const {simulate,profiles}=require('../tools/simulate_balance.cjs');for(const name of ['species','legendary','mixed']){const row=simulate({species:'deinonychus',build:{name,...profiles[name]},seconds:.1,mode:'duel'});assert.ok(Object.keys(row.startingMutations).length>0);assert.ok(Object.values(row.startingMutations).every(Number.isFinite));if(name==='legendary')assert.equal(row.startingMutations.deinoPrime,1);}});
