'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(species){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);g.start({seed:123});const r=g.run;r.enemies=[];r.spawnTimer=999;Object.assign(r.map,{rocks:[],mud:[],cover:[],sites:[],events:[],ponds:[]});return g;}
test('new species unlock with banked DNA and selection survives saving',()=>{for(const id of ['triceratops','pachycephalosaurus','gallimimus','baryonyx']){const g=new C.Game();g.phase='species';g.save.dna=200;assert.ok(g.unlockSpecies(id));assert.ok(g.selectSpecies(id));const saved=C.sanitizeSave(g.save);assert.equal(saved.selectedSpecies,id);assert.equal(saved.dna,200-C.PLAYER_SPECIES[id].cost);}});
test('Triceratops armour protects the front and leaves rear vulnerable',()=>{const g=setup('triceratops'),r=g.run;r.player.facing='E';const hp=r.health;g.damage(40,{x:520,y:340});assert.equal(r.health,hp-30);r.invulnerable=0;g.damage(40,{x:440,y:340});assert.equal(r.health,hp-70);});
test('Pachycephalosaurus stagger works on normal dinosaurs and does not lock bosses',()=>{const g=setup('pachycephalosaurus'),r=g.run;const e=g.spawn('compy',{x:520,y:340});g.resolveBite('E');assert.equal(e.stagger,.3);const boss=g.spawn('carnotaurus',{x:520,y:340},true);g.resolveBite('E');assert.equal(boss.stagger,0);});
test('Gallimimus eats plants and meat, but sprint does not grant basic invulnerability',()=>{const g=setup('gallimimus'),r=g.run;r.map.forage=[{id:'plant:test',kind:'plant',x:480,y:340,value:2,depleted:false}];for(let i=0;i<13;i++)g.step(.05,{eat:true});assert.equal(r.totalMeat,1);r.map.forage=[];const e=g.spawn('compy',{x:480,y:340});g.kill(e);r.enemies=[];for(let i=0;i<13;i++)g.step(.05,{eat:true});assert.ok(r.totalMeat>1);r.pounce=1;r.invulnerable=0;const hp=r.health;g.damage(10);assert.equal(r.health,hp-10);});
test('fishing consumes stamina and finite stock, stops on movement and freezes in mutation choices',()=>{const g=setup('baryonyx'),r=g.run;r.map.fishSchools=[{id:'fish:test',kind:'fish',x:480,y:340,stock:2,value:2}];g.step(.05,{eat:true});assert.ok(r.eating);g.phase='mutation';const frozen=JSON.stringify(r);g.step(.05,{eat:true});assert.equal(JSON.stringify(r),frozen);g.phase='playing';g.step(.05,{eat:true,x:1});assert.equal(r.eating,null);r.player.x=480;for(let i=0;i<25;i++)g.step(.05,{eat:true});assert.equal(r.map.fishSchools[0].stock,1);assert.equal(r.totalMeat,2);assert.equal(r.stamina,96);});
test('fish and plant supplies support full progression in every biome without lava fishing',()=>{for(let stage=0;stage<4;stage++)for(let seed=1;seed<=12;seed++){const m=C.createMap(stage,seed);assert.ok(m.forage.reduce((n,p)=>n+p.value,0)>=C.STAGES[stage].target);assert.ok(m.fishSchools.reduce((n,p)=>n+p.stock*p.value,0)>=C.STAGES[stage].target);assert.ok(m.ponds.every(p=>C.riverDistance(m,p)>150));}});
test('tradeoffs change both sides of their bargain',()=>{const g=setup('compy'),r=g.run;r.mutations.glassCannon=1;r.mutations.heavyMuscle=1;r.mutations.overclock=1;const e=g.spawn('compy',{x:520,y:340});g.resolveBite('E');assert.ok(Math.abs(e.hp-(18-6*1.45))<1e-8);r.invulnerable=0;const hp=r.health;g.damage(10);assert.ok(Math.abs(r.health-(hp-11.2))<1e-8);assert.equal(C.abilityCost(r),34);g.attack();assert.equal(r.attackCooldown,.4*.88);});
test('already owned mutations gain modest weight, caps stay excluded and species/rarities still apply',()=>{const m=C.MUTATIONS.find(m=>m.id==='teeth');assert.equal(C.mutationWeight(m,{teeth:0}),4);assert.equal(C.mutationWeight(m,{teeth:1}),4.8);assert.equal(C.mutationWeight(m,{teeth:2}),5.6);for(const id of Object.keys(C.PLAYER_SPECIES)){const g=setup(id),r=g.run;for(const m of C.MUTATIONS)r.mutations[m.id]=m.max;r.mutations.teeth=1;r.mutations.legs=1;r.mutations.heart=0;g.addXP(6);assert.deepEqual(new Set(r.choices),new Set(['teeth','legs','heart']));}});
test('coordinated Compy packs reserve at most two simultaneous windups',()=>{const g=setup('utahraptor'),r=g.run;const pack=Array.from({length:5},(_,i)=>g.spawn('compy',{x:500+i,y:340}));for(const e of pack){g.provoke(e);e.cooldown=0;}for(const e of pack)g.enemyStep(e,.01);assert.ok(pack.filter(e=>['windup','bite'].includes(e.mode)).length<=2);assert.equal(pack[0].packRole,'leader');assert.ok(pack.slice(1).some(e=>e.packRole==='flank'));});
