'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js');
function setup(species='deinonychus'){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);g.start({seed:123});g.run.enemies=[];g.run.map.rocks=[];g.run.spawnTimer=999;return g;}
test('Deinonychus starts free, preserves old choices and owns all five rarity ranks',()=>{assert.equal(new C.Game().save.selectedSpecies,'deinonychus');const reloaded=C.sanitizeSave(new C.Game().save);assert.equal(new Set(reloaded.unlockedSpecies).size,reloaded.unlockedSpecies.length);for(const id of ['velociraptor','compy','utahraptor'])assert.equal(C.sanitizeSave({selectedSpecies:id,unlockedSpecies:[id]}).selectedSpecies,id);assert.deepEqual(new Set(C.MUTATIONS.filter(m=>m.species==='deinonychus').map(m=>m.rarity)),new Set(['common','uncommon','rare','epic','legendary']));});
test('Deinonychus finte has no contact damage, costs 26 stamina and empowers one flanking bite',()=>{const g=setup(),r=g.run,e=g.spawn('carnotaurus',{x:r.player.x+35,y:r.player.y});e.hp=e.maxHP=500;e.facingX=1;e.facingY=0;g.step(.01,{x:1,pounce:true});assert.equal(r.stamina,74);assert.equal(e.hp,500);r.hitStop=0;e.facingX=1;e.facingY=0;g.resolveBite('E');assert.equal(e.hp,486.5);assert.equal(r.precisionTime,0);r.mutations.deinonychus_common=3;assert.equal(C.abilityCost(r),20);});
test('Compy calls existing friends and waits for four nearby packmates before attacks',()=>{const g=setup(),r=g.run,e=g.spawn('compy',{x:r.player.x+70,y:r.player.y});e.alert=true;e.lastAttackedAt=r.seconds;g.enemyStep(e,.05);assert.equal(e.mode,'rally');assert.equal(r.stats.damageTaken,0);for(let i=0;i<3;i++){const mate=g.spawn('compy',{x:e.x+30+i*10,y:e.y+20});mate.herdId=e.herdId;mate.alert=true;mate.lastAttackedAt=r.seconds;mate.hunger=.8;}e.hunger=.8;g.enemyStep(e,.05);assert.notEqual(e.mode,'rally');});
test('nest cannot be looted before death, territorial guardian detects intrusion, reward once',()=>{const g=setup(),r=g.run,e=g.spawn('carnotaurus',{x:r.player.x+100,y:r.player.y});e.guard=true;e.alert=false;e.homeX=r.player.x;e.homeY=r.player.y;const site={id:99,type:'nest',x:r.player.x,y:r.player.y,guardId:e.id,claimed:false};r.map.sites=[site];g.enemyStep(e,.01);assert.equal(e.alert,true);assert.equal(g.interact(),false);assert.equal(site.claimed,false);e.hp=0;g.kill(e);g.choose(r.choices[0]);r.enemies=[];g.phase='playing';assert.equal(site.guardDefeated,true);assert.equal(g.interact(),true);g.explore(true);assert.equal(site.claimed,true);const food=r.pickups.length;assert.equal(g.interact(),false);assert.equal(r.pickups.length,food);});
test('varied forage is deterministic and toxic mushrooms apply a bounded paused DoT',()=>{const g=setup('triceratops'),r=g.run;assert.deepEqual(new Set(r.map.forage.map(p=>p.foodType)),new Set(['herb','fruit','roots','mushrooms']));r.map.forage=[{id:'toxic',kind:'plant',foodType:'mushrooms',toxic:true,value:1,x:r.player.x,y:r.player.y}];g.eat(.61,{eat:true});assert.equal(r.poisonTime,6);const hp=r.health;g.pause();g.step(.05,{});assert.equal(r.poisonTime,6);g.resume();for(let i=0;i<140;i++)g.step(.05,{});assert.ok(r.health<hp&&r.health>=hp-6);assert.equal(r.poisonTime,0);});
test('Deinonychus legendary strengthens the finte bite by 30 percent, not all attacks; feeding grants no extra food',()=>{const g=setup(),r=g.run,e=g.spawn('carnotaurus',{x:r.player.x+35,y:r.player.y});e.hp=e.maxHP=500;e.facingX=1;e.facingY=0;r.precisionTime=2;r.mutations.deinoPrime=1;g.resolveBite('E');assert.ok(Math.abs(e.hp-(500-9*1.5*1.3))<1e-8);assert.equal(r.stats.finteHits,1);const hp=e.hp;g.resolveBite('E');assert.ok(Math.abs(e.hp-(hp-9))<1e-8);r.map.forage=[];r.pickups=[{id:99,kind:'meat',corpseId:99,value:3,x:r.player.x,y:r.player.y,rarity:0}];r.mutations.deinonychus_uncommon=3;const food=r.totalMeat;g.eat(.42,{eat:true});assert.equal(r.totalMeat,food+1);assert.equal(r.pickups[0].value,2);});
