'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core');
function make(seed=42){const g=new C.Game({random:()=>.5});g.start({seed});return g;}
test('Deinonychus is the free starter; old chosen Compy and purchased species survive migration',()=>{assert.equal(make().run.species,'deinonychus');assert.equal(C.PLAYER_SPECIES.velociraptor.cost,0);for(const id of ['compy','utahraptor'])assert.equal(C.sanitizeSave({selectedSpecies:id,unlockedSpecies:[id],dna:55}).selectedSpecies,id);});
test('eight named bosses progress through new maps, including repeat biomes, and keep mutations',()=>{const g=make(),r=g.run,seen=[];r.mutations.teeth=2;for(let i=0;i<C.LEVELS.length;i++){const l=g.currentLevel();assert.equal(r.levelIndex,i);assert.match(l.bossName,/ - /);assert.ok(C.suitableHabitat(l.biome,r.map,l.boss,r.map.habitats.find(p=>C.suitableHabitat(l.biome,r.map,l.boss,p))));seen.push(r.map);r.enemies=[];r.meat=l.target;r.spawnTimer=999;g.step(.01);const boss=r.enemies.find(e=>e.boss);assert.ok(boss);assert.equal(boss.kind,l.boss);assert.equal(boss.bossName,l.bossName);boss.hp=0;g.step(.01);assert.equal(g.phase,'cleared');assert.equal(g.nextStage(),true);assert.equal(r.mutations.teeth,2);}assert.equal(g.phase,'result');assert.equal(r.bosses,8);assert.equal(r.result.stage,8);assert.equal(r.dna,C.LEVELS.reduce((n,l)=>n+l.dna,0));assert.equal(new Set(seen.map(m=>m.seed)).size,8);assert.notDeepEqual(seen[0].rocks,seen[1].rocks);});
test('seed1993 enters the one-level Compy secret, normal seeds retain the full journey',()=>{const g=make(C.SECRET_SEED),r=g.run;assert.equal(r.secret,true);assert.equal(r.campaign.length,1);assert.match(g.currentLevel().name,/hemmelige/);assert.ok(r.enemies.filter(e=>e.thiefPack).length>=18);r.enemies=[];g.kill(g.spawn(g.currentLevel().boss,{x:900,y:900},true));g.phase='cleared';g.nextStage();assert.equal(r.result.victory,true);assert.equal(make(1994).run.campaign.length,8);});
test('tiny Compy thieves consume corpse food without awarding the player, depleted packs scatter',()=>{const g=make(),r=g.run;r.enemies=[];r.map.rocks=[];r.pickups=[];g.kill(g.spawn('parasaurolophus',{x:1000,y:900}));const e=g.spawn('compy',{x:1000,y:900});e.thiefPack=true;const before=r.pickups.find(p=>p.kind==='meat').value,food=r.totalMeat;g.scavenge(e,.81);assert.equal(r.pickups.find(p=>p.kind==='meat').value,before-1);assert.equal(r.totalMeat,food);assert.equal(e.radius,4);assert.equal(C.SPECIES.compy.meat,1);e.alert=true;g.enemyStep(e,.01);assert.equal(e.mode,'flee');assert.equal(e.speciesSkill,undefined);});
test('ordinary species abilities share baseline costs and cooldowns, telegraph and freeze during mutation choices',()=>{for(const kind of ['carnotaurus','triceratops','pachycephalosaurus','gallimimus','ankylosaurus','baryonyx','tyrannosaurus','compy']){const g=make(),r=g.run;r.enemies=[];r.map.rocks=[];const e=g.spawn(kind,{x:540,y:340});e.alert=true;e.skillCooldown=0;if(kind==='compy')e.hp=2;const c=C.PLAYER_SPECIES[kind];assert.equal(g.npcAbility(e,.01),true,kind);assert.equal(e.mode,'windup');assert.equal(e.stamina,100-c.abilityCost);assert.equal(e.skillCooldown,c.abilityCooldown);const snapshot=JSON.stringify(e);g.phase='mutation';g.step(.05);assert.equal(JSON.stringify(e),snapshot);g.phase='playing';e.timer=.001;g.npcAbility(e,.01);assert.notEqual(e.mode,'windup');}});
test('NPC skills ignore player mutations, bosses keep their independent attack pattern, Bary can only catch actual water fish',()=>{const g=make(),r=g.run;r.enemies=[];r.map.rocks=[];const e=g.spawn('carnotaurus',{x:540,y:340});e.alert=true;e.skillCooldown=0;r.mutations.overclock=3;r.mutations.pounce=3;g.npcAbility(e,.01);assert.equal(e.stamina,55);const boss=g.spawn('carnotaurus',{x:540,y:340},true);assert.equal(g.npcAbility(boss,.01),false);boss.cooldown=0;g.enemyStep(boss,.01);assert.equal(boss.mode,'windup');assert.equal(boss.speciesSkill,undefined);const b=g.spawn('baryonyx',{x:1000,y:900});r.map.fishSchools=[{x:1000,y:900,stock:2}];r.map.ponds=[];b.skillCooldown=0;assert.equal(g.npcAbility(b,.01),false);});
test('simulator starting biome respects the eight-level route; isolated seed1993 duels use the classic fixture',()=>{const {simulate}=require('../tools/simulate_balance.cjs'),build={upgrades:{},mutations:{}};const run=simulate({species:'velociraptor',seed:42,build,stage:1,seconds:.1});assert.equal(run.biome,1);assert.equal(run.stage,3);const duel=simulate({species:'velociraptor',seed:1993,build,mode:'duel',stage:3,seconds:.1});assert.equal(duel.biome,3);assert.equal(duel.route,4);assert.notEqual(duel.outcome,'victory');});
