'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../PRIMAL_RUN_Game/src/core.js'),S=require('../tools/simulate_balance.cjs');
function setup(species='compy'){const g=new C.Game({random:()=>.5});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);g.start({seed:12});g.run.enemies=[];g.run.map.rocks=[];g.run.map.mud=[];g.run.map.cover=[];g.run.map.ponds=[];g.run.map.events=[];g.run.spawnTimer=999;return g;}
test('runs are deterministic for identical seed/species/build and preserve timeout outcome',()=>{const config={species:'gallimimus',build:{name:'test',upgrades:{damage:1},mutations:{teeth:1}},seed:8,seconds:1,mode:'duel'};assert.deepEqual(S.simulate(config),S.simulate(config));assert.equal(S.simulate(config).outcome,'timeout');assert.throws(()=>S.validateBuild('compy',{mutations:{bleed:1}}));assert.throws(()=>S.validateBuild('compy',{upgrades:{health:6}}));});
test('all registered species and new profiles run without NaN metrics',()=>{for(const species of Object.keys(C.PLAYER_SPECIES)){const row=S.simulate({species,build:S.profiles.baseline,seed:1,seconds:2,mode:'duel'});for(const v of Object.values(row.stats))if(typeof v==='number')assert.ok(Number.isFinite(v));assert.equal(row.stats.summary.length>0,true);}});
test('albino rewards are epic, queued, paused, cannot repeat, and caps fall back to DNA',()=>{const g=setup(),r=g.run,e=g.spawn('parasaurolophus',{x:700,y:400});e.rare=true;g.kill(e);r.enemies=[];assert.ok(r.dna>=4);assert.equal(r.rareRewards,1);assert.ok(g.offerRareReward());assert.ok(r.choices.every(id=>C.MUTATIONS.find(m=>m.id===id).rarity==='epic'));const frozen=JSON.stringify(r);g.step(.05,{attack:true});assert.equal(JSON.stringify(r),frozen);g.choose(r.choices[0]);assert.equal(r.rareRewards,0);for(const m of C.MUTATIONS.filter(m=>m.rarity==='epic'&&(!m.species||m.species===r.species)))r.mutations[m.id]=m.max;r.rareRewards=1;const dna=r.dna;assert.equal(g.offerRareReward(),false);assert.equal(r.dna,dna+8);});
test('injuries slow only wounded normal animals and leave an actual trail',()=>{const g=setup(),r=g.run,e=g.spawn('parasaurolophus',{x:1000,y:700});e.hp=e.maxHP*.2;const x=e.x;g.travel(e,100,0);assert.ok(Math.abs(e.x-x-72)<1e-6);e.naturalTime=15;g.enemyStep(e,.5);assert.ok(r.decals.length>0);e.boss=true;const before=e.x;g.travel(e,100,0);assert.equal(e.x-before,100);});
test('field guide persists only nearby observations and sanitizes unknown species',()=>{const g=setup(),r=g.run,e=g.spawn('compy',{x:500,y:340});e.mode='bite';g.recordObservation(e);assert.deepEqual(g.save.fieldGuide.compy,{biomes:[0],attacks:['bite']});const far=g.spawn('tyrannosaurus',{x:1900,y:1700});g.recordObservation(far);assert.equal(g.save.fieldGuide.tyrannosaurus,undefined);assert.equal(C.sanitizeSave({fieldGuide:{fake:{},compy:{biomes:[0,0,999],attacks:['bite','unknown']}}}).fieldGuide.fake,undefined);});
test('telemetry records landed attacks, effective damage, distance and freezes in pause',()=>{const g=setup(),r=g.run;g.spawn('parasaurolophus',{x:520,y:340});r.player.facing='E';g.step(.05,{attack:true});for(let i=0;i<5;i++)g.step(.05);assert.equal(r.stats.attacks,1);assert.equal(r.stats.landedAttacks,1);assert.ok(r.stats.damageDealt>0);g.step(.05,{x:1});assert.ok(r.stats.distance>0);g.pause();const stats=JSON.stringify(r.stats);g.step(.05,{x:1,attack:true});assert.equal(JSON.stringify(r.stats),stats);});
test('two new tradeoffs affect mobility, vulnerability, feeding and stamina',()=>{const a=setup(),b=setup();b.run.mutations.lightFrame=2;a.step(.05,{x:1});b.step(.05,{x:1});assert.ok(b.run.player.x>a.run.player.x);a.damage(10);b.damage(10);assert.ok(b.run.stats.damageTaken>a.run.stats.damageTaken);const c=setup(),d=setup();d.run.mutations.metabolicRush=2;c.run.stamina=d.run.stamina=20;c.step(.05);d.step(.05);assert.ok(c.run.stamina>d.run.stamina);});
test('aggregates keep deaths/timeouts separate and report uncertainty',()=>{const rows=[{species:'compy',build:'base',mode:'run',outcome:'death',timeout:false,simulationSeconds:1,bosses:0,kills:0,food:0,dna:0,remainingHP:0},{species:'compy',build:'base',mode:'run',outcome:'timeout',timeout:true,simulationSeconds:2,bosses:0,kills:0,food:0,dna:0,remainingHP:10}];const [r]=S.summarize(rows);assert.equal(r.deaths,1);assert.equal(r.timeouts,1);assert.equal(r.wins,0);assert.ok(r.wilson95[1]>0);});
test('missed secrets accumulate across stages but per-stage results stay separate',()=>{const g=setup(),r=g.run;r.map.sites=[{claimed:false},{claimed:true}];r.map.events=[{claimed:false}];assert.equal(g.statistics().secretsMissed,2);g.phase='cleared';g.nextStage();const current=r.map.sites.filter(s=>!s.claimed).length+r.map.events.filter(e=>!e.claimed).length;assert.equal(g.statistics().secretsMissed,current+2);assert.equal(g.statistics(true).secretsMissed,current);});
test('field guide does not claim a roar before it was observed',()=>{const g=setup(),e=g.spawn('tyrannosaurus',{x:500,y:340});e.pattern=3;e.mode='rest';g.recordObservation(e);assert.deepEqual(g.save.fieldGuide.tyrannosaurus.attacks,[]);e.mode='slam';g.recordObservation(e);assert.deepEqual(g.save.fieldGuide.tyrannosaurus.attacks,['roar']);});
