const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {createPrimalCore}=require('../src/core.js');
const B=require('../balance.json'),checks=[];
function test(name,fn){fn();checks.push(name);}
const core=()=>createPrimalCore(B),tick=(c,n,input)=>{for(let i=0;i<n;i++)c.tick(.05,input);};
test('WASD/cardinal movement, diagonal normalization, stop retains facing',()=>{
 for(const [key,dir] of [['up','N'],['down','S'],['left','W'],['right','E']]){const c=core(),s=c.state;const ox=s.player.x,oy=s.player.y;c.tick(.05,{[key]:true});assert.equal(s.animation,'Walk_'+dir);assert(Math.abs(Math.hypot(s.player.x-ox,s.player.y-oy)-8)<1e-8);c.tick(.05);assert.equal(s.animation,'Idle_'+dir);assert.equal(s.frame,0);}
 const c=core();c.tick(.05,{up:true,right:true});assert(Math.abs(Math.hypot(c.state.player.x-480,c.state.player.y-320)-8)<1e-8);
});
test('blocked movement selects idle; fixed radius rejects rocks',()=>{const c=core();c.state.player={x:236,y:230};c.tick(.05,{up:true});assert.equal(c.state.player.y,230);assert.equal(c.state.animation,'Idle_N');assert(!c.valid(236,220,14));});
test('bite cooldown, kill removal, food, XP awarded once',()=>{const c=core();c.state.enemies=[];c.addEnemy(510,320);c.tick(.05,{bite:true});assert.equal(c.state.hunts,1);assert.equal(c.state.xp,4);assert.equal(c.state.enemies.length,0);const c2=c.addEnemy(510,320);c.tick(.05,{bite:true});assert.equal(c2.hp,1);tick(c,3);assert.equal(c.state.hunts,1);});
test('level-up immediately freezes ALL gameplay incl later enemies, food, bleed and animation',()=>{
 const c=core(),s=c.state;s.enemies=[];s.xp=4;c.addEnemy(510,320);const later=c.addEnemy(500,320);later.bleed=2;s.hp=50;
 c.tick(.05,{bite:true,right:true});assert.equal(s.phase,'mutation');assert.equal(later.touch,0);assert.equal(later.bleed,2);assert.equal(s.hp,50);assert.equal(s.food.length,3);
 const before=JSON.stringify(s);tick(c,100,{bite:true,up:true});assert.equal(JSON.stringify(s),before);assert(c.choose('legs'));assert.equal(s.mutations.legs,1);assert.equal(s.phase,'playing');
});
test('overflow XP requires one choice per level; mutations stack',()=>{const c=core(),s=c.state;s.xp=40;c.tick(.05);assert.equal(s.level,2);c.choose('legs');assert.equal(s.phase,'mutation');assert.equal(s.level,3);c.choose('legs');assert.equal(s.phase,'mutation');c.choose('teeth');assert.equal(s.phase,'playing');assert.equal(s.mutations.legs,2);assert.equal(s.mutations.teeth,1);const ox=s.player.x;c.tick(.05,{right:true});assert(Math.abs(s.player.x-ox-10.4)<1e-8);assert(!c.choose('legs'));});
test('teeth stacks increase bleed; feathers regenerate stamina from balance.json',()=>{const c=core(),s=c.state;s.enemies=[];s.mutations.teeth=2;const e=c.addEnemy(540,320);e.hp=4;c.tick(.05,{bite:true});assert.equal(e.hp,3);tick(c,9);assert.equal(e.hp,2);s.mutations.feathers=3;s.stamina=50;c.tick(.05);assert(Math.abs(s.stamina-51.44)<1e-8);});
test('food consumed once and max HP enforced',()=>{const c=core(),s=c.state;s.food=[];s.hp=90;c.addFood(480,320);c.tick(.05);assert.equal(s.hp,100);assert.equal(s.food.length,0);s.hp=50;c.tick(.05);assert.equal(s.hp,50);});
test('death stops simulation; run DNA awarded once; restart clears all run state',()=>{const c=core(),s=c.state;s.hunts=5;s.time=31;s.hp=1;s.enemies=[];c.addEnemy(480,320);c.tick(.05);assert.equal(s.phase,'dead');assert.equal(s.dna,4);const before=JSON.stringify(s);tick(c,50,{right:true,bite:true});assert.equal(JSON.stringify(s),before);c.reset();assert.equal(c.state.phase,'playing');assert.equal(c.state.hp,100);assert.equal(c.state.xp,0);assert.equal(c.state.awarded,false);assert.deepEqual(c.state.mutations,{teeth:0,legs:0,feathers:0});assert.equal(c.state.enemies.length,1);});
test('pounce uses balance stamina/cooldown and feathers stacks',()=>{const c=core();c.state.enemies=[];c.tick(.05,{right:true,pounce:true});assert.equal(c.state.stamina,70);assert(Math.abs(c.state.player.x-498.4)<1e-8);c.tick(.05,{pounce:true});assert(c.state.stamina>70);assert(c.state.pounceCooldown>0);});
test('balance enemy variants: prey flees harmlessly, carnotaurus HP/damage/XP, bleed kills once',()=>{const c=core(),s=c.state;s.enemies=[];const prey=c.addEnemy(510,320,'parasaurolophus');c.tick(.05);assert(prey.x>510);assert.equal(s.hp,100);s.enemies=[];s.mutations.teeth=2;const e=c.addEnemy(540,320,'carnotaurus');assert.equal(e.hp,3);c.tick(.05,{bite:true});assert.equal(e.hp,2);tick(c,19);assert.equal(s.hunts,1);assert.equal(s.phase,'mutation');assert.equal(s.level,2);c.choose('legs');tick(c,2);assert.equal(s.hunts,1);});
const p=require('../project.json'),player=p.layouts[0].objects.find(o=>o.name==='Player');
test('all 28 player frames have identical world-space torso mask and exact origin',()=>{for(const a of player.animations)for(const f of a.directions[0].sprites){const origin=f.originPoint;assert.deepEqual(f.customCollisionMask[0].map(v=>[v.x-origin.x,v.y-origin.y]),[[-14,-14],[14,-14],[14,14],[-14,14]]);}});
fs.mkdirSync(path.join(__dirname,'../reports'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../reports/core-tests.json'),JSON.stringify({result:'PASS',checks,scope:'Deterministic kernel + generated project structure, NOT graphical GDevelop runtime'},null,2)+'\n');console.log(checks.length+' kernel/structure tests PASS');
