#!/usr/bin/env python3
"""Builds PRIMAL_RUN_Game/src/lang.js from the translation tables in tools/i18n/.
Tables map the exact Danish text (numbers as #, key names as @) to each language.
Run: python tools/i18n/build_lang.py  (then npm run build:game)"""
import json, pathlib, sys
here = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(here))
from tr_core import CORE
from tr_ui import UI
from tr_records import RECORDS
from tr_part_b import PART_B
from tr_fun import TLH, SJN
LANGS = ['en', 'de', 'sv', 'no', 'ja', 'zh']
dicts = {l: {} for l in LANGS}
seen = {}
for row in CORE + UI + RECORDS + PART_B:
    da, *rest = row
    if len(rest) != len(LANGS):
        raise SystemExit(f'Row needs {len(LANGS)} translations: {da}')
    if da in seen and seen[da] != rest:
        print('note: duplicate key with different text, keeping first:', da)
        continue
    seen[da] = rest
    for lang, text in zip(LANGS, rest):
        if text.count('#') != da.count('#') or text.count('@') != da.count('@'):
            raise SystemExit(f'Placeholder mismatch in {lang}: {da!r} -> {text!r}')
        dicts[lang][da] = text
# Per-language JSON dictionaries (tools/i18n/lang/<code>/*.json, see STYLE_GUIDE.md). A file for an existing
# language overrides the table rows (game-term fixes); new codes become new languages (fallback English).
import re
for folder in sorted((here / 'lang').glob('*')):
    if not folder.is_dir():
        continue
    code = folder.name
    entries = {}
    for f in sorted(folder.glob('*.json')):
        entries.update(json.loads(f.read_text(encoding='utf-8')))
    for da, text in entries.items():
        if text.count('#') != da.count('#') or text.count('@') != da.count('@') or sorted(re.findall(r'\{\d\}', text)) != sorted(re.findall(r'\{\d\}', da)):
            raise SystemExit(f'Placeholder mismatch in {code}: {da!r} -> {text!r}')
    dicts.setdefault(code, {}).update(entries)
dicts['tlh'] = {**TLH, **dicts.get('tlh', {})}
dicts['sjn'] = {**SJN, **dicts.get('sjn', {})}
out = ['/* GENERATED by tools/i18n/build_lang.py from tools/i18n/tr_*.py. Edit the tables, not this file. */',
       "(function(root){'use strict';const I=root.PrimalI18n;if(!I)return;"]
for lang, d in dicts.items():
    out.append(f'I.add({json.dumps(lang)},{json.dumps(d, ensure_ascii=False, separators=(",", ":"))});')
out.append("})(typeof globalThis!=='undefined'?globalThis:this);")
target = here.parent.parent / 'PRIMAL_RUN_Game/src/lang.js'
target.write_text('\n'.join(out) + '\n', encoding='utf-8')
print('wrote', target, {k: len(v) for k, v in dicts.items()})
