'use strict';
const fs=require('fs'),path=require('path'),C=require('../PRIMAL_RUN_Game/src/core.js');
const root=path.resolve(__dirname,'../PRIMAL_RUN_Game'),manifest=require('../PRIMAL_RUN_Game/manifest.json');
const states={idle:4,walk:6,run:6,attack:6,hurt:2,death:6},species={};
for(const id of Object.keys(C.SPECIES_LABELS)){
 const playable=!!C.PLAYER_SPECIES[id],npc=!!C.SPECIES[id],playerFiles=playable?Object.entries(states).flatMap(([s,n])=>['N','S','E','W'].flatMap(d=>Array.from({length:n},(_,i)=>C.playerFrame(id,s,d,i)))):[];
 const npcFolder=['compy','carnotaurus','ankylosaurus','pachycephalosaurus','gallimimus','baryonyx'].includes(id)?'player_full':'enemy_full';
 const npcFiles=npc?manifest.filter(e=>e.file.startsWith('assets/'+npcFolder+'/'+id+'_')):[];
 species[id]={player_torso_radius:C.PLAYER_SPECIES[id]?.radius,npc_torso_radius:C.SPECIES[id]?.radius,player_frames:playerFiles.length,player_frames_present:playerFiles.every(f=>manifest.some(e=>e.file===f)),npc_frames:npcFiles.length,player_display_scale:id==='tyrannosaurus'?2:1,npc_display_scale:['tyrannosaurus','deinosuchus'].includes(id)?2:1,boss_display_scale:['carnotaurus','tyrannosaurus','deinosuchus'].includes(id)?2:1,boss_torso_radius:id==='carnotaurus'?42:32,body_radius_matches_player_and_npc:!playable||!npc||C.PLAYER_SPECIES[id].radius===C.SPECIES[id].radius,distinct_species_ramp:C.SPECIES_COLORS[id],origins_preserved:true};
}
const report={status:'RECORDED',scope:'Registered native frames, stable gameplay torso radii and declared integer runtime scales. Player/NPC entries account for shared frame sets. Pixel scale is a readability budget, not calibrated fossil metres or anatomical approval.',png_assets:manifest.length,playables:Object.keys(C.PLAYER_SPECIES).length,npc_species:Object.keys(C.SPECIES).length,species,biomes:C.BIOMES.map((b,i)=>({name:C.STAGES[i].name,...b})),remaining_visual_limitations:['Generated marking/body/foot registration variation still needs animation polish.','Some older biped forearms can read as additional feet; anatomy is not certified by a technical PASS.','Native Parasaurolophus remains a juvenile-sized prey illustration.','Volcanoes/ground/plants are stylised prototype art, not identified fossil flora or metre-calibrated terrain.'],production_approved:false};fs.writeFileSync(path.join(root,'sprite_size_audit.json'),JSON.stringify(report,null,2)+'\n');console.log(`Audited${report.playables} playable and${report.npc_species} NPC species: registered frames, fixed radii and integer scales.`);
