#!/usr/bin/env python3
"""Builds PRIMAL_RUN_Game/src/run_titles.js from the reviewed title catalogue
docs/design/records-world-extinction/data/run_titles.json (95 titles + fallback).
Conditions become plain functions over the RunSummary `s`, so the game never evals text.
Every `s.<name>` must be declared in data/run_summary_variables.json.
Run: python tools/build_run_titles.py  (then npm run build:game)"""
import json, pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
data = root / 'docs/design/records-world-extinction/data'
catalogue = json.loads((data / 'run_titles.json').read_text(encoding='utf-8'))
variables = json.loads((data / 'run_summary_variables.json').read_text(encoding='utf-8'))
errors, out = [], []
for t in catalogue['titles']:
    used = set(re.findall(r'\bs\.([A-Za-z_]\w*)', t['condition']))
    if used - set(variables):
        errors.append(f"{t['id']}: undeclared {sorted(used - set(variables))}")
    if re.search(r"[;{}`\\]|\b(function|new|import|eval|this|window|globalThis)\b", t['condition']):
        errors.append(f"{t['id']}: unexpected characters in condition")
    fields = {k: t[k] for k in ('id', 'name', 'description', 'condition', 'priority', 'rarity', 'tieBreak', 'category', 'requiredVariables', 'implementationStatus')}
    out.append('    Object.assign(' + json.dumps(fields, ensure_ascii=False, separators=(',', ':')) + ',{test:s=>(' + t['condition'] + ')})')
if len(catalogue['titles']) != 96:
    errors.append(f"expected 96 titles, found {len(catalogue['titles'])}")
if errors:
    raise SystemExit('\n'.join(errors))
code = ('/* GENERATED by tools/build_run_titles.py from docs/design/records-world-extinction/data/run_titles.json. Edit the JSON, not this file. */\n'
        "(function (root, factory) {\n  if (typeof module === 'object' && module.exports) module.exports = factory();\n  else root.PrimalRunTitles = factory();\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this, function () {\n  'use strict';\n"
        '  return { rarityOrder: ' + json.dumps(catalogue['rarityOrder']) + ', titles: [\n' + ',\n'.join(out) + '\n  ] };\n});\n')
target = root / 'PRIMAL_RUN_Game/src/run_titles.js'
target.write_text(code, encoding='utf-8', newline='\n')
print('wrote', target.relative_to(root), len(catalogue['titles']), 'titles')
