'use strict';
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '..'), game = path.join(root, 'PRIMAL_RUN_Game');
const out = path.join(root, 'dist');
fs.mkdirSync(out, { recursive: true });
// Ship game and optional sprite-review evidence; omit source art and GDevelop project.
for (const name of ['PART_A_REUSE_VALIDATION.json','part_a_review.html','part_a_runtime_report.json','SPRITE_RULES_LIMP.md','forage_manifest.json','forage_validation.json','SPRITE_RULES_FORAGE.md','hud_attack_review.html','avatar_manifest.json','avatar_validation.json','species_attack_manifest.json','species_attack_animations.json','species_attack_validation.json','SPRITE_RULES_AVATARS.md','SPRITE_RULES_SPECIES_ATTACKS.md','OVERLAPPING_DISCOVERIES.md','deinosuchus_playable_review.html','deinosuchus_playable_manifest.json','deinosuchus_playable_validation.json','SPRITES_AND_MECHANICS_STATUS.md','IDEABANK.md','MISSING_SPRITES.md','OVERHAUL_2026-10.md','JOURNEY_AND_COMPY.md','journey_validation_report.json','journey_runtime_report.json','journey_player_runtime_report.json','journey_enemy_runtime_report.json','WATER_AND_BARYONYX_FIX.md','water_fishing_runtime_report.json','bary_n_runtime_report.json','corpse_anatomy_review.json','corpse_scenes_runtime_report.json','RESEARCH_AND_ECOLOGY.md','corpse_manifest.json','corpse_validation.json','SPRITE_RULES_CORPSES.md','SPECIES_ANATOMY.md','research_runtime_report.json','carrion_rex_runtime_report.json','CARRION_AND_REX.md','fishing_manifest.json','fishing_validation.json','SPRITE_RULES_FISHING.md','CODE_AUDIT.md','combat_feedback_runtime_report.json','COMBAT_FEEDBACK.md','eating_priorities_5_8_runtime_report.json','eating_priorities_5_8_gdevelop_report.json','PRIORITIES_5_8.md','priorities_1_4_runtime_report.json','enemy_full_review.html', 'enemy_full_manifest.json','enemy_full_animations.json','enemy_full_validation.json','enemy_full_runtime_report.json','terrain_runtime_report.json','balance_audit.json','PRIORITIES_1_4.md','SPRITE_RULES_ENEMY_FULL.md','index.html', 'PATCH_NOTES.html', 'style.css', 'music_manifest.json', 'adaptive_runtime_report.json', 'src', 'assets', 'sounds', 'player_review.html', 'player_full_review.html', 'ecology_review.html', 'NEXT_IMPROVEMENTS.md', 'ecology_manifest.json', 'ecology_validation.json', 'sprite_size_audit.json', 'jungle_runtime_report.json', 'SPRITE_RULES_ECOLOGY.md', 'player_full_manifest.json', 'player_full_animations.json', 'player_full_validation.json', 'player_full_runtime_report.json', 'SPRITE_RULES_PLAYER_FULL.md', 'SPRITE_RULES.md', 'SPRITE_RULES_v1_reference.md', 'SPRITE_RULES_v2_reference.md', 'player_combat_animations.json', 'player_sprite_validation.json', 'enemy_review.html', 'enemy_animations.json', 'enemy_sprite_validation.json', 'enemy_animation_manifest.json', 'enemy_animation_runtime_report.json', 'world_runtime_report.json', 'polish_runtime_report.json', 'roguelite_runtime_report.json', 'palette.json', 'SPRITE_RULES_ENEMIES.md']) {
  fs.cpSync(path.join(game, name), path.join(out, name), { recursive: true });
}
fs.cpSync(path.join(game, 'previews/player_full'), path.join(out, 'previews/player_full'), {recursive:true});
fs.cpSync(path.join(game, 'previews/ecology'), path.join(out, 'previews/ecology'), {recursive:true});
fs.cpSync(path.join(game, 'previews/layout'), path.join(out, 'previews/layout'), {recursive:true});
fs.cpSync(path.join(game,'previews/enemy_full'),path.join(out,'previews/enemy_full'),{recursive:true});
fs.cpSync(path.join(game,'previews/combat-feedback'),path.join(out,'previews/combat-feedback'),{recursive:true});
fs.cpSync(path.join(game,'previews/corpses'),path.join(out,'previews/corpses'),{recursive:true});
fs.cpSync(path.join(game,'balance_runs'),path.join(out,'balance_runs'),{recursive:true});
fs.cpSync(path.join(game,'previews/deinosuchus'),path.join(out,'previews/deinosuchus'),{recursive:true});
for(const family of ['avatars','species_attacks','followup','forage','part_a'])fs.cpSync(path.join(game,'previews',family),path.join(out,'previews',family),{recursive:true});
fs.writeFileSync(path.join(out, '.nojekyll'), '');
console.log('Built static browser game in dist/. All paths are relative for GitHub Pages.');
