#!/usr/bin/env node
'use strict';
// Shared gameplay core, no invulnerability, reward boosts, HP edits or forced wins.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),C=require('../PRIMAL_RUN_Game/src/core.js');
const CORE_SHA=crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../PRIMAL_RUN_Game/src/core.js'))).digest('hex');
function rng(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=Math.imul(x^x>>>15,1|x);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
const profiles={baseline:{upgrades:{},mutations:{}},offence:{upgrades:{damage:3},mutations:{teeth:2,quick:2}},survival:{upgrades:{health:3,regen:3},mutations:{armor:2,scavenger:2}},tradeoff:{upgrades:{digestion:2},mutations:{glassCannon:2,heavyMuscle:2,overclock:2}},mobility:{upgrades:{regen:3},mutations:{lightFrame:2,metabolicRush:2}},species:{upgrades:{},mutations:{},speciesRanks:2}};
function validateBuild(species,build){if(!Object.hasOwn(C.PLAYER_SPECIES,species))throw Error('Unknown playable species '+species);for(const [id,rank]of Object.entries(build.mutations||{})){const m=C.MUTATIONS.find(m=>m.id===id);if(!m||m.species&&m.species!==species||!Number.isInteger(rank)||rank<0||rank>m.max)throw Error('Invalid mutation '+id+' for '+species);}for(const [id,rank]of Object.entries(build.upgrades||{})){const u=C.UPGRADES.find(u=>u.id===id);if(!u||!Number.isInteger(rank)||rank<0||rank>u.max)throw Error('Invalid DNA upgrade '+id);}}
function steer(r,x,y){let dx=x-r.player.x,dy=y-r.player.y,n=Math.hypot(dx,dy);if(n<2)return {x:0,y:0};dx/=n;dy/=n;const blocked=(vx,vy)=>r.map.rocks.some(rock=>Math.hypot(r.player.x+vx*50-rock.x,r.player.y+vy*50-rock.y)<r.player.radius+rock.radius+8);if(blocked(dx,dy)){for(const a of [.8,-.8,1.5,-1.5,2.5]){const vx=dx*Math.cos(a)-dy*Math.sin(a),vy=dx*Math.sin(a)+dy*Math.cos(a);if(!blocked(vx,vy))return{x:vx,y:vy};}}return{x:dx,y:dy};}
function bot(g,t,policy='cautious'){const r=g.run,p=r.player,config=C.PLAYER_SPECIES[r.species],dist=e=>Math.hypot(e.x-p.x,e.y-p.y),nearest=items=>items.filter(Boolean).sort((a,b)=>dist(a)-dist(b))[0];
 const boss=nearest(r.enemies.filter(e=>e.boss)),threat=nearest(r.enemies.filter(e=>e.damage&&dist(e)<160));
 const warning=nearest(r.enemies.filter(e=>['windup','charge','slam','bite'].includes(e.mode)&&dist(e)<e.attackRadius+70));
 if(warning&&policy==='cautious'){const dx=p.x-warning.x,dy=p.y-warning.y,n=Math.hypot(dx,dy)||1;return{...steer(r,p.x-dy/n*130,p.y+dx/n*130),attack:true,pounce:r.stamina>=C.abilityCost(r)};}
 if(!boss){const diet=config.diet,foods=[];if(['herbivore','omnivore'].includes(diet))foods.push(...r.map.forage.filter(f=>!f.depleted));if(diet==='piscivore')foods.push(...r.map.fishSchools.filter(f=>f.stock>0));if(diet!=='herbivore')foods.push(...r.pickups.filter(f=>f.corpseId!==undefined));const food=nearest(foods);if(food&&(!threat||dist(food)<100)){if(dist(food)<42)return{eat:true};return steer(r,food.x,food.y);}}
 const target=boss||nearest(r.enemies.filter(e=>!e.guard));if(!target)return steer(r,480+Math.cos(t*.02)*300,340+Math.sin(t*.02)*200);
 if(dist(target)<config.range+target.radius-10){return{...steer(r,target.x,target.y),attack:true,pounce:['ankylosaurus','tyrannosaurus'].includes(r.species)&&!!threat};}
 return {...steer(r,target.x,target.y),attack:true,pounce:dist(target)<170&&r.stamina>75&&['carnotaurus','triceratops','pachycephalosaurus','baryonyx'].includes(r.species)};
}
function simulate({species,build,seed=1,seconds=180,mode='run',target='carnotaurus',dt=1/30,policy='cautious',stage=0,boss=false}){
 validateBuild(species,build);if(!['cautious','aggressive'].includes(policy))throw Error('Unknown bot policy');const g=new C.Game({random:rng(seed^0xABCDEF)});g.save.unlockedSpecies=Object.keys(C.PLAYER_SPECIES);g.selectSpecies(species);Object.assign(g.save.upgrades,build.upgrades);g.start({seed,campaign:mode==='duel'?'classic':'journey'});if(!Number.isInteger(stage)||stage<0||stage>3)throw Error('Invalid starting biome');if(mode==='duel'&&g.run.secret){g.run.secret=false;g.run.campaign=C.STAGES.map((v,i)=>({...v,biome:i}));}if(mode==='run'&&g.run.secret&&stage>0)throw Error('Secret seed has only biome0');while(g.run.stage<stage){g.phase='cleared';g.nextStage();}const r=g.run;Object.assign(r.mutations,build.mutations);if(build.speciesRanks)for(const m of C.MUTATIONS.filter(m=>m.species===species&&m.rarity!=='legendary'))r.mutations[m.id]=Math.min(m.max,build.speciesRanks);
 // Starting mutations are scenario grants, NOT affordable normal starts.
 for(const [id,rank]of Object.entries(r.mutations)){if(id==='heart'){r.maxHealth+=15*rank;r.health+=15*rank;}if(id==='apexGenome'&&rank){r.maxHealth+=25;r.health+=25;}}
 if(mode==='duel'){if(!Object.hasOwn(C.SPECIES,target))throw Error('Unknown target '+target);r.enemies=[];r.pickups=[];r.map.rocks=[];r.map.mud=[];r.map.cover=[];r.map.ponds=[];r.map.events=[];r.map.sites=[];r.map.forage=[];r.map.fishSchools=[];r.spawnTimer=1e9;g.spawn(target,{x:620,y:340},boss);}
 let wall=0,timeout=false,duelWin=false;
 while(wall<seconds&&g.phase!=='result'){
  if(g.phase==='mutation'){const picks=r.choices.map(id=>C.MUTATIONS.find(m=>m.id===id));const wanted=picks.find(m=>['teeth','armor','quick','scavenger','heart'].includes(m.id))||picks[0];g.choose(wanted.id);continue;}
  if(g.phase==='cleared'){g.nextStage();continue;}
  const input=bot(g,wall,policy);g.step(dt,input);g.drainEvents();wall+=dt;
  if(mode==='duel'&&r.kills){duelWin=true;break;}
 }
 timeout=wall>=seconds&&g.phase!=='result'&&!duelWin;
 const price=Object.entries(build.upgrades||{}).reduce((sum,[id,rank])=>sum+Array.from({length:rank},(_,i)=>C.upgradeCost(i)).reduce((a,b)=>a+b,0),0);
 return {species,seed,mode,policy,target:mode==='duel'?target:null,bossTarget:boss,startingStage:stage,build:build.name||'custom',outcome:duelWin?'duel_win':r.result?.victory?'victory':r.result?'death':'timeout',timeout,simulationSeconds:+r.seconds.toFixed(2),wallBudgetSeconds:+wall.toFixed(2),stage:r.levelIndex+1,biome:r.stage,route:r.campaign.length,bosses:r.bosses,kills:r.kills,food:r.totalMeat,dna:r.dna,remainingHP:+r.health.toFixed(2),stats:g.statistics(),startingUpgradeDNACost:price,unlockDNA:C.PLAYER_SPECIES[species].cost,startingMutations:{...build.mutations},mutations:r.mutations};
}
function summarize(rows){const groups={};for(const row of rows){const key=row.species+'/'+row.build+'/'+row.mode;(groups[key]||=[]).push(row);}return Object.entries(groups).map(([group,items])=>{const wins=items.filter(r=>['victory','duel_win'].includes(r.outcome)).length,n=items.length,p=wins/n,z=1.96,den=1+z*z/n,centre=(p+z*z/(2*n))/den,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;const mean=key=>items.reduce((sum,r)=>sum+r[key],0)/n;return {group,runs:n,wins,deaths:items.filter(r=>r.outcome==='death').length,timeouts:items.filter(r=>r.timeout).length,botWinRate:p,wilson95:[centre-half,centre+half],meanSeconds:mean('simulationSeconds'),meanBosses:mean('bosses'),meanKills:mean('kills'),meanFood:mean('food'),meanDNA:mean('dna'),meanHP:mean('remainingHP')};});}
function main(){if(process.argv.includes('--help')){console.log('Seeded shared-core balance experiments\n--runs N --seconds N --seed N --species all|id,id\n--profiles baseline,offence,survival,tradeoff,mobility,species\n--config JSON ({builds:[{name,upgrades,mutations}]}) --out PATH\n--mode run|duel --policy cautious|aggressive --target NPC_ID --boss true|false --stage 0..3\nTimeouts are not wins. Starting mutations are research grants.');return;}const args=process.argv.slice(2),get=(key,fallback)=>{const i=args.indexOf('--'+key);return i<0?fallback:args[i+1];};const runs=Number(get('runs',10)),seconds=Number(get('seconds',180)),seed=Number(get('seed',42)),mode=get('mode','run');if(!Number.isInteger(runs)||runs<1||runs>10000||!Number.isFinite(seconds)||seconds<=0||seconds>7200||!['run','duel'].includes(mode))throw Error('Invalid runs, seconds or mode');const species=get('species','all')==='all'?Object.keys(C.PLAYER_SPECIES):get('species','').split(',');const builds=get('config',null)?JSON.parse(fs.readFileSync(get('config'),'utf8')).builds:get('profiles','baseline,offence,survival,tradeoff,species').split(',').map(name=>{if(!profiles[name])throw Error('Unknown profile '+name);return{name,...profiles[name]};});const out=path.resolve(get('out','/tmp/primal-balance'));fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'runs.jsonl'),'');const rows=[];for(const id of species)for(const build of builds)for(let i=0;i<runs;i++){const row=simulate({species:id,build,seed:seed+i,seconds,mode,target:get('target','carnotaurus'),policy:get('policy','cautious'),stage:Number(get('stage',0)),boss:get('boss','false')==='true'});rows.push(row);fs.appendFileSync(path.join(out,'runs.jsonl'),JSON.stringify(row)+'\n');if(i===runs-1)console.error(id+'/'+build.name+': '+runs+' completed');}const report={version:1,coreSHA256:CORE_SHA,policy:get('policy','cautious')+'-movement-aim-v3',seed,runsPerScenario:runs,seconds,dt:1/30,mode,builds,target:get('target','carnotaurus'),bossTarget:get('boss','false')==='true',startingStage:Number(get('stage',0)),scope:'Bot-controlled shared Game.step; normal maps/AI/rewards in run mode. Duel mode explicitly removes environment and adds one ordinary or boss target. Scenario starting mutations are granted research builds, not normal starts. Timeouts remain timeouts. Does not estimate human win rates or prove balance.',summary:summarize(rows),runs:rows};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');const cols=['group','runs','wins','deaths','timeouts','botWinRate','meanSeconds','meanBosses','meanKills','meanFood','meanDNA','meanHP'];fs.writeFileSync(path.join(out,'summary.csv'),cols.join(',')+'\n'+report.summary.map(r=>cols.map(k=>r[k]).join(',')).join('\n')+'\n');console.log(JSON.stringify({out,runs:rows.length,summary:report.summary},null,2));}
if(require.main===module)main();module.exports={simulate,summarize,validateBuild,profiles};
